import test from 'node:test'
import assert from 'node:assert/strict'

import { canvasText } from '../src/shared/canvasText.ts'

const CAP = 8000

test('drops script and style bodies', () => {
  const { text } = canvasText(
    '<style>body{color:red}.x::after{content:"hi"}</style><p>Real text</p><script>const a=1<2</script>',
    CAP
  )
  assert.equal(text, 'Real text')
})

test('keeps table cells apart', () => {
  const html = `<table>
    <tr><th>Tool</th><th>Cold start</th></tr>
    <tr><td>Vite</td><td>2.1s</td></tr>
    <tr><td>webpack</td><td>14.8s</td></tr>
  </table>`
  const { text } = canvasText(html, CAP)
  assert.equal(text, 'Tool | Cold start\nVite | 2.1s\nwebpack | 14.8s')
})

test('block closes become line breaks, inline tags do not', () => {
  const { text } = canvasText(
    '<h1>Audit</h1><p>The <strong>slow</strong> query is <code>SELECT *</code>.</p><ul><li>One</li><li>Two</li></ul>',
    CAP
  )
  assert.equal(text, 'Audit\nThe slow query is SELECT * .\nOne\nTwo')
})

test('<br> and <hr> break lines', () => {
  const { text } = canvasText('a<br>b<br/>c<hr />d', CAP)
  assert.equal(text, 'a\nb\nc\nd')
})

test('nested wrappers do not each earn a blank line', () => {
  // Three closes in a row is structure, not spacing: every block break is one
  // newline, so the reading never has a gap the document did not show.
  const { text } = canvasText('<div><div><p>One</p></div></div><p>Two</p>', CAP)
  assert.equal(text, 'One\nTwo')
})

test('source indentation between rows is formatting, not a blank line', () => {
  const spaced = '<table>\n  <tr><td>a</td></tr>\n\n  <tr><td>b</td></tr>\n</table>'
  assert.equal(canvasText(spaced, CAP).text, 'a\nb')
})

test('decodes the entities authored HTML actually contains', () => {
  const { text } = canvasText(
    '<p>a &amp; b &lt;tag&gt; &quot;q&quot; &nbsp; &mdash; &#39;s&#39; &#x2713;</p>',
    CAP
  )
  assert.equal(text, 'a & b <tag> "q" — \'s\' ✓')
})

test('leaves an unknown or malformed entity as written', () => {
  const { text } = canvasText('<p>&notanentity; &#xZZ; 50&percnt;</p>', CAP)
  assert.match(text, /&notanentity;/)
  assert.match(text, /&#xZZ;/)
})

test('a comment is not content', () => {
  const { text } = canvasText('<!-- generated by the agent --><p>Body</p>', CAP)
  assert.equal(text, 'Body')
})

test('truncates on a line boundary and says so', () => {
  const rows = Array.from({ length: 200 }, (_, i) => `<tr><td>row ${i}</td><td>${i}</td></tr>`)
  const { text, truncated } = canvasText(`<table>${rows.join('')}</table>`, 300)
  assert.equal(truncated, true)
  assert.ok(text.length <= 300)
  // Cut between rows, not through one: the last line is a whole row.
  assert.match(text.split('\n').at(-1)!, /^row \d+ \| \d+$/)
})

test('a short document is not reported truncated', () => {
  const { text, truncated } = canvasText('<p>Short</p>', CAP)
  assert.equal(truncated, false)
  assert.equal(text, 'Short')
})

test('falls back to a hard cut when no line break is near the cap', () => {
  const { text, truncated } = canvasText(`<p>${'x'.repeat(500)}</p>`, 100)
  assert.equal(truncated, true)
  assert.equal(text.length, 100)
})

test('empty and tag-only input are empty, not a crash', () => {
  assert.equal(canvasText('', CAP).text, '')
  assert.equal(canvasText('<div><span></span></div>', CAP).text, '')
  assert.equal(canvasText(undefined as unknown as string, CAP).text, '')
})

test('a whole document reduces to its readable text', () => {
  const html = `<!doctype html><html><head><meta charset="utf-8">
    <title>Query Audit</title>
    <style>:root{color-scheme:light dark}body{font:14px system-ui}</style>
    </head><body>
    <h1>Query Audit</h1>
    <p>Three queries account for <strong>81%</strong> of wall time.</p>
    <table><thead><tr><th>Query</th><th>Calls</th></tr></thead>
    <tbody><tr><td>listFeed</td><td>1,204</td></tr></tbody></table>
    <script>document.querySelectorAll('th').forEach(sort)</script>
    </body></html>`
  const { text } = canvasText(html, CAP)
  // The <title> is dropped, so the name is not said twice before the body.
  assert.equal(text.startsWith('Query Audit\n'), true)
  assert.equal(text.split('Query Audit').length - 1, 1)
  assert.ok(!text.includes('color-scheme'), 'style body leaked')
  assert.ok(!text.includes('querySelectorAll'), 'script body leaked')
  assert.match(text, /Query Audit/)
  assert.match(text, /81% of wall time/)
  assert.match(text, /listFeed \| 1,204/)
})

test('a rich cell does not split its row', () => {
  // `<td><p>…</p></td>` is ordinary authored HTML, and its block close would
  // otherwise cut the row in half and strand the remaining columns.
  const html =
    '<table><tr><td><p>Redis</p></td><td>61ms<br>p50</td><td><strong>94%</strong></td></tr></table>'
  assert.equal(canvasText(html, CAP).text, 'Redis | 61ms p50 | 94%')
})

test('a list inside a cell stays on the row', () => {
  const html = '<table><tr><td><ul><li>a</li><li>b</li></ul></td><td>ok</td></tr></table>'
  assert.equal(canvasText(html, CAP).text, 'a b | ok')
})
